In [1]:
!python --version


Python 3.7.12 :: Intel Corporation


In [2]:
import numpy as np

In [3]:
x=[1,2,3,4,5,6]

In [6]:
np_x=np.array(x)
print(type(np_x))


<class 'numpy.ndarray'>


In [7]:
print(x*4)
print(np_x*4)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[ 4  8 12 16 20 24]


In [8]:
np_x.ndim

1

In [9]:
np_x.shape

(6,)

In [17]:
y=[1,2,3,"hello"]
np_y=np.array(y)

In [20]:
print(np_y)

['1' '2' '3' 'hello']


In [19]:
k=[1,2,3,4,"tete"]
np_k=np.array(k)
print(np_k)

['1' '2' '3' '4' 'tete']


In [21]:
np_x

array([1, 2, 3, 4, 5, 6])

In [22]:
np_x.dtype

dtype('int32')

In [23]:
np_x.data

In [24]:
np_x+4

array([ 5,  6,  7,  8,  9, 10])

In [25]:
x3=[[2,7]   ,       [3,4]]
print(x3)

[[2, 7], [3, 4]]


In [26]:
np_x3=np.array(x3)

In [27]:
print(np_x3)

[[2 7]
 [3 4]]


In [28]:
print(type(np_x3))

<class 'numpy.ndarray'>


In [29]:
np_x3.ndim

2

In [30]:
np_x3.shape

(2, 2)

In [32]:
np_x3.dtype##4bytes

dtype('int32')

In [33]:
np_x3.data

In [34]:
print(np_x3.shape)
print(np_x3.strides)


(2, 2)
(8, 4)


In [35]:
np.random.rand(5)

array([0.48630321, 0.81204741, 0.0306954 , 0.96170491, 0.23799877])

In [36]:
np.random.rand(4,4)

array([[0.53289113, 0.62740795, 0.77207717, 0.08073566],
       [0.65603344, 0.39126425, 0.2043957 , 0.3240778 ],
       [0.55010192, 0.6331792 , 0.60690408, 0.02169566],
       [0.33635191, 0.10872057, 0.14875409, 0.75146996]])

In [37]:
np.random.randn(4)

array([ 0.19207221, -0.67671182,  0.88641351, -0.21290183])

In [38]:
np.random.rand(5)

array([0.62211461, 0.40467701, 0.33520394, 0.48530134, 0.73608923])

In [39]:
np.random.rand(4,4)

array([[0.45122111, 0.44396094, 0.83443172, 0.63659878],
       [0.70351248, 0.70942359, 0.90932589, 0.24938627],
       [0.19235041, 0.95484497, 0.32643315, 0.61653284],
       [0.44537018, 0.12906577, 0.95432534, 0.11073474]])

In [41]:
x4=np.array([1,2,1,2,3,4,3])

In [43]:
np.unique(x4)

array([1, 2, 3, 4])

In [44]:
np.dot(x4)

TypeError: dot() missing 1 required positional argument: 'b'

In [45]:
np.dot(x4,2)

array([2, 4, 2, 4, 6, 8, 6])

In [47]:
np.power(x4,2)

array([ 1,  4,  1,  4,  9, 16,  9], dtype=int32)

In [48]:
np.sqrt(x4)

array([1.        , 1.41421356, 1.        , 1.41421356, 1.73205081,
       2.        , 1.73205081])

In [57]:
np.ones(x4)

array([[[[[[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]],


          [[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]]]],




        [[[[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]],


          [[[1., 1., 1.],
          

In [50]:
np.zeros(x4)

array([[[[[[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]],


          [[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]]]],




        [[[[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]],


          [[[0., 0., 0.],
          

In [51]:
np.max(x4)

4

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x5=np.random.rand(4,4)

In [59]:
x5

array([[0.8581562 , 0.67866612, 0.09273175, 0.52659501],
       [0.51507334, 0.71950895, 0.1317324 , 0.66545981],
       [0.54474098, 0.38084093, 0.40375262, 0.57251779],
       [0.60120661, 0.08843172, 0.18145425, 0.87690874]])

In [61]:
np.amin(x5,axis=0)

array([0.51507334, 0.08843172, 0.09273175, 0.52659501])

In [62]:
np.amin(x5,axis=1)

array([0.09273175, 0.1317324 , 0.38084093, 0.08843172])

In [65]:
np.mean(x5,axis=1)

array([0.53903727, 0.50794362, 0.47546308, 0.43700033])

In [66]:
np.std(x5,axis=1)

array([0.28314154, 0.22975909, 0.08413499, 0.3190952 ])

In [67]:
height_inches=[61,65,76,78,82,78]
np_h=np.array(height_inches)

In [68]:
weight_pounds=[100,126,178,110,130,140]
np_w=np.array(weight_pounds)

In [81]:
np_h_m=np_h*.0245 ##height in m
np_h_m

array([1.4945, 1.5925, 1.862 , 1.911 , 2.009 , 1.911 ])

In [82]:
np_w_kg=np_w*.453 #weight in kg
np_w_kg

array([45.3  , 57.078, 80.634, 49.83 , 58.89 , 63.42 ])

In [83]:
np_bmi=np_w_kg/(np_h_m**2)

In [84]:
np_bmi

array([20.28179381, 22.50659858, 23.25727623, 13.64487348, 14.59088656,
       17.36620261])

In [85]:
MASK=np_bmi>20
print(MASK)

[ True  True  True False False False]


In [86]:
np_bmi[MASK]

array([20.28179381, 22.50659858, 23.25727623])